export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const LOAD_CUSTOMER_COUNT_SUCCESS = 'LOAD_CUSTOMER_COUNT_SUCCESS';

export const LOAD_CUSTOMER_DATA_SUCCESS = 'LOAD_CUSTOMER_DATA_SUCCESS';

export const LOAD_METER_COUNT_SUCCESS = 'LOAD_METER_COUNT_SUCCESS';

export const LOAD_READINGS_GRAPH_TOTAL_DAILY_WATER_CONSUMPTION = 'LOAD_READINGS_GRAPH_TOTAL_DAILY_WATER_CONSUMPTION';